-- Create the table if it doesn't exist
create table if not exists public.federal_districts (
  id bigint generated by default as identity not null,
  name_en text null,
  name_fr text null,
  geom geometry null,
  constraint federal_districts_pkey primary key (id)
) TABLESPACE pg_default;

-- Create index on geometry if it doesn't exist
CREATE INDEX IF NOT EXISTS federal_districts_geom_idx ON public.federal_districts USING GIST (geom);

-- Create the function
CREATE OR REPLACE FUNCTION public.find_federal_district(lat double precision, lng double precision)
 RETURNS text
 LANGUAGE sql
 STABLE
AS $function$
  SELECT name_en
  FROM public.federal_districts
  WHERE ST_Contains(geom, ST_SetSRID(ST_Point(lng, lat), 4326))
  LIMIT 1;
$function$
